### ISSUE TITLE
May be something wrong about the code of "Versatile-Filter"

### ISSUE THREAD

**Issue by GuideWsp** [huawei-noah/Versatile-Filters#1]
https://github.com/huawei-noah/Versatile-Filters/blob/master/vcnn.py#L56

The original code is:
weight1 = self.weight[:, :ch_len, s:self.kernel_size[0]-s, s:self.kernel_size[0]-s]

I think it should be as the Fig2(b) in the paper:
weight1 = self.weight[:, start:start+ch_len, s:self.kernel_size[0]-s, s:self.kernel_size[0]-s]

is it right?

**Comment by iamhankai** [comment]
You are right. Thanks for your comment.

Channel versatile filters can have multiple flexible ways to implement, but not limited to the original paper. I think the given code is an alternative implementation for channel versatile filters.

**Comment by GuideWsp** [comment]
Yes. I agree with "Channel versatile filters can have multiple flexible ways to implement, but not limited to the original paper".

**Comment by YunheWang** [comment]
> Yes. I agree with "Channel versatile filters can have multiple flexible ways to implement, but not limited to the original paper".

Basicaly, the two ways for implementing channel versatile filters can achieve comparable performance. :)

**Comment by Haus226** [comment]
I think the original code emphasizes "sharing the same weights" across all input channels, ensuring that every channel influences the weight update. In contrast, this approach allows only a subset of input channels to be involved in weight updates (a little bit of cross interaction of channels?), similar to group convolution when the number of groups equals to the c_hat. Am I right?
