### ISSUE TITLE
Two ways of Channel Versatile Filters

### ISSUE THREAD

**Issue by Haus226** [huawei-noah/Versatile-Filters#2]
https://github.com/iamhankai/Versatile-Filters/issues/1#issue-494954964

Hi, I think the original code emphasizes "sharing the same weights" across all input channels, ensuring that every channel influences the weight update. In contrast, this approach allows only a subset of input channels to be involved in weight updates (a little bit of cross interaction of input channels since the update of weight is sliding along input channels dimension?), similar to group convolution when the number of channels in a group is c_hat. Am I right?

**Comment by iamhankai** [comment]
Yes, you're right.

**Comment by Haus226** [comment]
Alright, thank you for the innovative work!
